// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanTraSua.Data;

#nullable disable

namespace QuanTraSua.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260324235617_UpdateOrderAndSeedData")]
    partial class UpdateOrderAndSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("QuanTraSua.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderDetails")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("QuanTraSua.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Đậm vị trà ô long, trân châu dai giòn.",
                            ImageUrl = "https://tocotocotea.com/wp-content/uploads/2021/12/O-Long-Thai-Cuc.png",
                            Name = "Trà Sữa Trân Châu Ô Long",
                            Price = 35000m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Bột matcha nguyên chất từ Nhật.",
                            ImageUrl = "https://tocotocotea.com/wp-content/uploads/2021/12/Tra-Sua-Matcha.png",
                            Name = "Trà Sữa Matcha Nhật Bản",
                            Price = 40000m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Sữa tươi nguyên chất mix đường đen.",
                            ImageUrl = "https://tocotocotea.com/wp-content/uploads/2021/12/Sua-Tuoi-Tran-Chau-Duong-Den.png",
                            Name = "Sữa Tươi Trân Châu Đường Đen",
                            Price = 45000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
